//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int Id { get; set; }
        public string Category { get; set; }
        public int Number { get; set; }
        public string Description { get; set; }
        public float Price { get; set; }
        public int CountOfPlaces { get; set; }
        public int CountOfPartRooms { get; set; }
        public string Statut { get; set; }
    }
}
